- name: Provision
  hosts: all
  roles:
    - role: common
      tags:
        - common
    - role: user
      tags:
        - user
    - role: tailscale
      tags:
        - tailscale
    - role: podman
      tags:
        - podman
